/*
 * generated by Xtext
 */
package fr.obeo.intent.specification;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpecificationRuntimeModule extends fr.obeo.intent.specification.AbstractSpecificationRuntimeModule {

}
