/*
* generated by Xtext
*/
package fr.obeo.intent.specification.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpecificationAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/obeo/intent/specification/parser/antlr/internal/InternalSpecification.tokens");
	}
}
