/*
* generated by Xtext
*/
package fr.obeo.intent.specification.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.obeo.intent.specification.services.SpecificationGrammarAccess;

public class SpecificationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SpecificationGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.obeo.intent.specification.parser.antlr.internal.InternalSpecificationParser createParser(XtextTokenStream stream) {
		return new fr.obeo.intent.specification.parser.antlr.internal.InternalSpecificationParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Specification";
	}
	
	public SpecificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpecificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
