/*
* generated by Xtext
*/
package fr.obeo.intent.specification.ui.contentassist;

import fr.obeo.intent.specification.ui.contentassist.AbstractSpecificationProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SpecificationProposalProvider extends AbstractSpecificationProposalProvider {

}
