/*
* generated by Xtext
*/
package fr.obeo.intent.specification.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import fr.obeo.intent.specification.services.SpecificationGrammarAccess;

public class SpecificationParser extends AbstractContentAssistParser {
	
	@Inject
	private SpecificationGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected fr.obeo.intent.specification.ui.contentassist.antlr.internal.InternalSpecificationParser createParser() {
		fr.obeo.intent.specification.ui.contentassist.antlr.internal.InternalSpecificationParser result = new fr.obeo.intent.specification.ui.contentassist.antlr.internal.InternalSpecificationParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSpecificationAccess().getGroup(), "rule__Specification__Group__0");
					put(grammarAccess.getSpecificationAccess().getGroup_2(), "rule__Specification__Group_2__0");
					put(grammarAccess.getSpecificationAccess().getGroup_2_2(), "rule__Specification__Group_2_2__0");
					put(grammarAccess.getSpecificationAccess().getGroup_3(), "rule__Specification__Group_3__0");
					put(grammarAccess.getSpecificationAccess().getGroup_3_2(), "rule__Specification__Group_3_2__0");
					put(grammarAccess.getSpecificationAccess().getGroup_4(), "rule__Specification__Group_4__0");
					put(grammarAccess.getSpecificationAccess().getGroup_4_2(), "rule__Specification__Group_4_2__0");
					put(grammarAccess.getAutomationLayerAccess().getGroup(), "rule__AutomationLayer__Group__0");
					put(grammarAccess.getAutomationLayerAccess().getGroup_2(), "rule__AutomationLayer__Group_2__0");
					put(grammarAccess.getAutomationLayerAccess().getGroup_6(), "rule__AutomationLayer__Group_6__0");
					put(grammarAccess.getAutomationLayerAccess().getGroup_10(), "rule__AutomationLayer__Group_10__0");
					put(grammarAccess.getFeatureAccess().getGroup(), "rule__Feature__Group__0");
					put(grammarAccess.getFeatureAccess().getGroup_2(), "rule__Feature__Group_2__0");
					put(grammarAccess.getStoryAccess().getGroup(), "rule__Story__Group__0");
					put(grammarAccess.getStoryAccess().getGroup_2(), "rule__Story__Group_2__0");
					put(grammarAccess.getStoryAccess().getGroup_3(), "rule__Story__Group_3__0");
					put(grammarAccess.getStoryAccess().getGroup_4(), "rule__Story__Group_4__0");
					put(grammarAccess.getScenarioAccess().getGroup(), "rule__Scenario__Group__0");
					put(grammarAccess.getScenarioAccess().getGroup_2(), "rule__Scenario__Group_2__0");
					put(grammarAccess.getScenarioAccess().getGroup_2_2(), "rule__Scenario__Group_2_2__0");
					put(grammarAccess.getScenarioAccess().getGroup_3(), "rule__Scenario__Group_3__0");
					put(grammarAccess.getScenarioAccess().getGroup_3_2(), "rule__Scenario__Group_3_2__0");
					put(grammarAccess.getScenarioAccess().getGroup_4(), "rule__Scenario__Group_4__0");
					put(grammarAccess.getScenarioAccess().getGroup_4_2(), "rule__Scenario__Group_4_2__0");
					put(grammarAccess.getSpecificationAccess().getNameAssignment_1(), "rule__Specification__NameAssignment_1");
					put(grammarAccess.getSpecificationAccess().getRolesAssignment_2_1(), "rule__Specification__RolesAssignment_2_1");
					put(grammarAccess.getSpecificationAccess().getRolesAssignment_2_2_1(), "rule__Specification__RolesAssignment_2_2_1");
					put(grammarAccess.getSpecificationAccess().getCapabilitiesAssignment_3_1(), "rule__Specification__CapabilitiesAssignment_3_1");
					put(grammarAccess.getSpecificationAccess().getCapabilitiesAssignment_3_2_1(), "rule__Specification__CapabilitiesAssignment_3_2_1");
					put(grammarAccess.getSpecificationAccess().getBenefitsAssignment_4_1(), "rule__Specification__BenefitsAssignment_4_1");
					put(grammarAccess.getSpecificationAccess().getCapabilitiesAssignment_4_2_1(), "rule__Specification__CapabilitiesAssignment_4_2_1");
					put(grammarAccess.getSpecificationAccess().getAutomationLayerAssignment_5(), "rule__Specification__AutomationLayerAssignment_5");
					put(grammarAccess.getSpecificationAccess().getFeaturesAssignment_6(), "rule__Specification__FeaturesAssignment_6");
					put(grammarAccess.getSpecificationAccess().getStoriesAssignment_7(), "rule__Specification__StoriesAssignment_7");
					put(grammarAccess.getAutomationLayerAccess().getContextAssignment_1(), "rule__AutomationLayer__ContextAssignment_1");
					put(grammarAccess.getAutomationLayerAccess().getContextAssignment_2_1(), "rule__AutomationLayer__ContextAssignment_2_1");
					put(grammarAccess.getAutomationLayerAccess().getActionsAssignment_5(), "rule__AutomationLayer__ActionsAssignment_5");
					put(grammarAccess.getAutomationLayerAccess().getActionsAssignment_6_1(), "rule__AutomationLayer__ActionsAssignment_6_1");
					put(grammarAccess.getAutomationLayerAccess().getBehavioursAssignment_9(), "rule__AutomationLayer__BehavioursAssignment_9");
					put(grammarAccess.getAutomationLayerAccess().getBehavioursAssignment_10_1(), "rule__AutomationLayer__BehavioursAssignment_10_1");
					put(grammarAccess.getContextAccess().getNameAssignment(), "rule__Context__NameAssignment");
					put(grammarAccess.getActionAccess().getNameAssignment(), "rule__Action__NameAssignment");
					put(grammarAccess.getBehaviourAccess().getNameAssignment(), "rule__Behaviour__NameAssignment");
					put(grammarAccess.getFeatureAccess().getNameAssignment_1(), "rule__Feature__NameAssignment_1");
					put(grammarAccess.getFeatureAccess().getRefFeaturesAssignment_2_1(), "rule__Feature__RefFeaturesAssignment_2_1");
					put(grammarAccess.getFeatureAccess().getStoriesAssignment_3(), "rule__Feature__StoriesAssignment_3");
					put(grammarAccess.getStoryAccess().getNameAssignment_1(), "rule__Story__NameAssignment_1");
					put(grammarAccess.getStoryAccess().getAsAssignment_2_1(), "rule__Story__AsAssignment_2_1");
					put(grammarAccess.getStoryAccess().getIWantAssignment_3_1(), "rule__Story__IWantAssignment_3_1");
					put(grammarAccess.getStoryAccess().getSoThatAssignment_4_1(), "rule__Story__SoThatAssignment_4_1");
					put(grammarAccess.getStoryAccess().getScenariosAssignment_5(), "rule__Story__ScenariosAssignment_5");
					put(grammarAccess.getScenarioAccess().getNameAssignment_1(), "rule__Scenario__NameAssignment_1");
					put(grammarAccess.getScenarioAccess().getGivenAssignment_2_1(), "rule__Scenario__GivenAssignment_2_1");
					put(grammarAccess.getScenarioAccess().getGivenAssignment_2_2_1(), "rule__Scenario__GivenAssignment_2_2_1");
					put(grammarAccess.getScenarioAccess().getWhenAssignment_3_1(), "rule__Scenario__WhenAssignment_3_1");
					put(grammarAccess.getScenarioAccess().getWhenAssignment_3_2_1(), "rule__Scenario__WhenAssignment_3_2_1");
					put(grammarAccess.getScenarioAccess().getThenAssignment_4_1(), "rule__Scenario__ThenAssignment_4_1");
					put(grammarAccess.getScenarioAccess().getThenAssignment_4_2_1(), "rule__Scenario__ThenAssignment_4_2_1");
					put(grammarAccess.getRoleAccess().getNameAssignment(), "rule__Role__NameAssignment");
					put(grammarAccess.getCapabilityAccess().getNameAssignment(), "rule__Capability__NameAssignment");
					put(grammarAccess.getBenefitAccess().getNameAssignment(), "rule__Benefit__NameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			fr.obeo.intent.specification.ui.contentassist.antlr.internal.InternalSpecificationParser typedParser = (fr.obeo.intent.specification.ui.contentassist.antlr.internal.InternalSpecificationParser) parser;
			typedParser.entryRuleSpecification();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SpecificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpecificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
