<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="specification"
    nsURI="http://www.eclipse.org/intent/specification" nsPrefix="specification">
  <eClassifiers xsi:type="ecore:EClass" name="Specification" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" lowerBound="1"
        upperBound="-1" eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="automationLayer" eType="#//AutomationLayer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stories" upperBound="-1"
        eType="#//Story" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benefits" upperBound="-1"
        eType="#//Benefit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilities" upperBound="-1"
        eType="#//Capability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Capability" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Benefit" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Story" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="as" lowerBound="1" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soThat" lowerBound="1"
        eType="#//Benefit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" lowerBound="1"
        upperBound="-1" eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iWant" lowerBound="1" eType="#//Capability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="given" lowerBound="1" upperBound="-1"
        eType="#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" lowerBound="1" upperBound="-1"
        eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" upperBound="-1"
        eType="#//Behaviour"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//ScenarioElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//ScenarioElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Behaviour" eSuperTypes="#//ScenarioElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutomationLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" upperBound="-1"
        eType="#//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviours" upperBound="-1"
        eType="#//Behaviour" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
        eType="#//Note" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationNote" eSuperTypes="#//Note"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestNote" eSuperTypes="#//Note"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioElement" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestGenerationNote" eSuperTypes="#//Note">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TestType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestType">
    <eLiterals name="unit"/>
    <eLiterals name="plugin" value="1"/>
    <eLiterals name="ui" value="2"/>
  </eClassifiers>
</ecore:EPackage>
