/*
 * generated by Xtext
 */
package fr.obeo.intent.specification.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpecificationUiModule extends fr.obeo.intent.specification.ui.AbstractSpecificationUiModule {
	public SpecificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
