/*
 * generated by Xtext
 */
package fr.obeo.intent.specification.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.obeo.intent.specification.ui.internal.SpecificationActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpecificationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SpecificationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SpecificationActivator.getInstance().getInjector(SpecificationActivator.FR_OBEO_INTENT_SPECIFICATION_SPECIFICATION);
	}
	
}
